# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: go-server
  labels:
    app: go-server
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: go-server
  type: ClusterIP
